name: Create Issue on Push

on:
  push:
    branches:
      - main

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Create Issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueTitle = `New Push on ${process.env.GITHUB_REF_NAME}`;
            const issueBody = `A new push has been made to \`${process.env.GITHUB_REF_NAME}\` branch. Please check the updates.`;
            const labels = ['done'];
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: labels
            });
