name: Create Issue with File Links

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        run: |
          echo "::set-output name=list::$(git diff --name-only HEAD^ HEAD | xargs -I {} echo \"{}\" | tr '\n' ',')"

      - name: Create Issue with Links
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            async function run() {
              const repositoryUrl = context.payload.repository.html_url;
              const changedFiles = "${{ steps.changed-files.outputs.list }}".slice(0, -1).split(',');
              const changedFilesLinks = changedFiles.map(file => `[${file}](${repositoryUrl}/blob/main/${file})`).join('\n');

              const issueBody = `This issue is automatically generated from the last commit on the main branch.\n\n### Changed Files:\n${changedFilesLinks}`;

              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Automatically Generated Issue from Push',
                body: issueBody,
                labels: ['auto-generated'],
              });
            }
            
            run().catch(err => console.error(err));
