name: Create Issue with File Links

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        run: |
          echo "::set-output name=list::$(git diff --name-only HEAD^ HEAD | xargs -I {} echo \"- {}\" | tr '\n' ',')"

      - name: Get last commit message
        id: last-commit-message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Create Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            async function run() {
              const repositoryUrl = context.payload.repository.html_url;
              const changedFilesRaw = "${{ steps.changed-files.outputs.list }}";
              const changedFiles = changedFilesRaw.slice(0, -1).split(',').map(file => `- [${file}](${repositoryUrl}/blob/main/${file.replace(' ', '%20')})`).join('\n');

              const issueTitle = "Changes detected in push";
              const commitMessage = "${{ steps.last-commit-message.outputs.message }}";
              const issueBody = `This issue is automatically generated from the last commit on the main branch.\n\n**Commit message:**\n${commitMessage}\n\n### Changed Files:\n${changedFiles}`;

              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issueTitle,
                body: issueBody,
                labels: ['auto-generated'],
              });
            }

            run().catch(err => console.error(err));
