name: Create Issue from Commit and Link to Project

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # 이전 커밋과 비교하기 위해 필요한 깊이

      - name: Get changed files
        id: changed-files
        run: |
          echo "::set-output name=list::$(git diff --name-only HEAD^ HEAD | xargs -I {} echo \"- {}\" | tr '\n' ',' )"
        shell: bash
      
      - name: Get last commit message
        id: last-commit-message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Create Issue and Add Assignees
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            async function run() {
              const now = new Date();
              const formattedNow = now.toISOString().replace('T', ' ').substring(0, 16);
              const commitMessage = "${{ steps.last-commit-message.outputs.message }}";
              const changedFilesList = "${{ steps.changed-files.outputs.list }}".slice(0, -1).split(',').join('\n');
              const issueTitle = `[${formattedNow}] ${commitMessage}`;
              const issueBody = `This issue is automatically generated from the last commit on the main branch.\n\n### Changed Files:\n${changedFilesList}`;
              const labels = ['auto-generated'];

              // 이슈 생성
              const issueCreationResponse = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issueTitle,
                body: issueBody,
                labels: labels
              });

              console.log(`Issue created: ${issueCreationResponse.data.html_url}`);
            }

            // 함수 실행
            run().catch(err => console.error(err));
