name: Create Issue from Commit and Link to Project

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # 이전 커밋과 비교하기 위해 필요

      - name: Get changed files
        id: changed-files
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          cat changed_files.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const now = new Date();
            now.setHours(now.getHours() + 9); // KST로 변환
            const formattedNow = now.toISOString().replace('T', ' ').substring(0, 16).replace('Z', '');

            const commitMessage = `${process.env.COMMIT_MESSAGE}`;
            const changedFiles = process.env.CHANGED_FILES.split('\n').filter(line => line).map(file => `- [${file}](${context.payload.repository.html_url}/blob/${{ github.ref }}/blob/main/${file})`).join('\n');
            
            const issueTitle = `[${formattedNow}] ${commitMessage}`;
            const issueBody = `
              This issue is automatically generated from the last commit on the main branch.
              
              ### Changed Files
              ${changedFiles}
            `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['auto-generated'],
            });
              console.log(`Issue created: ${response.data.html_url}`);
            }
            
            run().catch(err => console.error(err));
        env:
          COMMIT_MESSAGE: ${{ steps.last-commit-message.outputs.message }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.list }}